// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RequestPermission.Api.Infrastracture;

#nullable disable

namespace RequestPermission.Api.Migrations
{
    [DbContext(typeof(RequestPermissionContext))]
    [Migration("20240414164218_addingFirstMig")]
    partial class addingFirstMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RequestPermission.Api.Entity.Department", b =>
                {
                    b.Property<int>("D_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("D_ID"));

                    b.Property<string>("D_NAME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("D_ID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("RequestPermission.Api.Entity.Employee", b =>
                {
                    b.Property<Guid>("E_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("E_DEPARTMENT")
                        .HasColumnType("int");

                    b.Property<string>("E_EMAIL")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("E_NAME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("E_SURNAME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("E_TITLE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("E_ID");

                    b.HasIndex("E_DEPARTMENT");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("RequestPermission.Api.Entity.Vacation", b =>
                {
                    b.Property<Guid>("V_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("V_EMP_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("V_END_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("V_REASON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("V_START_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("V_TYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("V_ID");

                    b.HasIndex("V_EMP_ID");

                    b.ToTable("Vacations");
                });

            modelBuilder.Entity("RequestPermission.Api.Entity.Employee", b =>
                {
                    b.HasOne("RequestPermission.Api.Entity.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("E_DEPARTMENT")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("RequestPermission.Api.Entity.Vacation", b =>
                {
                    b.HasOne("RequestPermission.Api.Entity.Employee", "V_EMP")
                        .WithMany()
                        .HasForeignKey("V_EMP_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("V_EMP");
                });

            modelBuilder.Entity("RequestPermission.Api.Entity.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
